### ISSUE TITLE
syncing with Forkers doesn't seem to work

### ISSUE THREAD

**Issue by dave256** [drewmccormack/Forked#4]
This probably isn't the right place for this but I saw a link to this - maybe on Mastodon but can't seem to find now so can't reply there. I downloaded the Forkers app from the App Store on both my iPhone and my iPad but no syncing seems to happen. Both are signed into the same iCloud account. When I add different data on either device it doesn't show up on the other device. Am I missing something? Thanks.

**Comment by drewmccormack** [comment]
Are you signed into iCloud Drive on both devices? Ie not just iCloud, but with iCloud Drive turned on?

**Comment by drewmccormack** [comment]
OK, I'm an idiot. I forgot to deploy the CloudKit schema to production. Classic beginner's error.

It should work now. Let me know.

**Comment by dave256** [comment]
@drewmccormack yes, it work nows. I experimented with Ensembles (purchased it for a year quite a while ago) but never ended up adding syncing to my app. I'll be curious to try this out next summer when I have time (I teach computer science and develop apps as a hobby). The app I'd like to use it for seems better suited for Core Data or Swift Data (but that seems to still have some rough edges from what I've read) as there are relationships between the different objects in my data. I need to read more about Forked but is it reasonable to use when the data has relationships or should I stick with Core Data or Swift Data for that and Forked is better when you just have arrays of structs and no relationships between different structs?

**Comment by drewmccormack** [comment]
I think it can work fine, even when you have relationships. I intend to use it myself in such a case.

The philosophy is a bit different though. With Forked, you would put anything that is naturally a part of something else (component) as a nested struct. Eg a `Car` might have `Wheels`, and you would get...

```swift
@ForkedModel
struct Car: Identifiable {
     var id: UUID = .init()
     @Merged var wheels: Set<Wheel> = []
}

@ForkedModel
struct Wheel {
      ...
}
```

This works when you have "ownership", ie one thing "owns" the other.

When you just have relationships, like with `Company` and `Employee`, you would just store ids. So you would get...

```swift
@ForkedModel
struct Employee: Identifiable {
    var id: String
    var companyId: Company.ID
}
```

If you wanted the company of an employee, you would get the id and then go and find the Company. It is less "magic" than SwiftData, but it is simple, and that is also nice sometimes.

**Comment by dave256** [comment]
@drewmccormack thanks for the info. I'll experiment with it when I have time as in theory this sounds like it should make resolving merge conflicts more automatic.
